export const MAP_STYLE_SOURCE_IDS = {
  SMART_SEOUL_RASTER: "smart-seoul-raster",
  SMART_SEOUL_MOSAIC: "smart-seoul-mosaic",
} as const;

export const MAP_STYLE_LAYER_IDS = {
  MAP_BACKGROUND: "map-background",
  SMART_SEOUL_RASTER: "smart-seoul-raster",
  SMART_SEOUL_MOSAIC: "smart-seoul-mosaic",
} as const;

export const MAP_STYLE_COLORS = {
  EMPTY_BACKGROUND: "#e8ebe4",
  SMART_SEOUL_MOSAIC_FALLBACK: "#5f665f",
} as const;

export const SMART_SEOUL_MAP_KIND = "base";
export const SMART_SEOUL_MAP_ID = "dawul_kor_normal";
export const SMART_SEOUL_TILE_SIZE = 256;
export const SMART_SEOUL_TMS_MIN_ZOOM = 7;
export const SMART_SEOUL_TMS_MAX_ZOOM = 19;
export const SMART_SEOUL_TMS_INITIAL_ZOOM = 19;
export const SMART_SEOUL_TILE_GROUP_SIZE = 50;
export const SMART_SEOUL_TILE_ORIGIN = [90112, 2765760] as const;
export const SMART_SEOUL_RESOLUTIONS = [
  2048, 1024, 512, 256, 128, 64, 32, 16, 8, 4, 2, 1, 0.5, 0.25,
] as const;
export const SMART_SEOUL_TILE_EXTENT = [90112, 1192896, 2187264, 2765760] as const;

export const SMART_SEOUL_MOSAIC_ZOOM = 12;
export const SMART_SEOUL_MOSAIC_TILE_RADIUS = 2;
export const SMART_SEOUL_MOSAIC_REFRESH_TILE_SPAN = 3;
export const SMART_SEOUL_MOSAIC_LOOKAHEAD_METERS = 450;
export const SMART_SEOUL_MOSAIC_MAX_CONCURRENT_TILE_REQUESTS = 4;
export const SMART_SEOUL_MOSAIC_TILE_CACHE_LIMIT = 180;

export const SMART_SEOUL_RASTER_PROTOCOL = "smartseoul";
export const SMART_SEOUL_RASTER_TILE_TEMPLATE = `${SMART_SEOUL_RASTER_PROTOCOL}://raster/{z}/{x}/{y}`;

export const EPSG_5179_PROJECTION = {
  FALSE_EASTING: 1_000_000,
  FALSE_NORTHING: 2_000_000,
  LATITUDE_OF_ORIGIN: 38,
  CENTRAL_MERIDIAN: 127.5,
  SCALE_FACTOR: 0.9996,
  GRS80_SEMI_MAJOR_AXIS: 6_378_137,
  GRS80_INVERSE_FLATTENING: 298.257222101,
} as const;

export const EPSG_5179_INVERSE_PROJECTION = {
  LONGITUDE_DEGREE_METER_APPROXIMATION: 88_000,
  LATITUDE_DEGREE_METER_APPROXIMATION: 111_000,
  REFINEMENT_ITERATIONS: 10,
  WGS84_METERS_PER_LATITUDE_DEGREE: 111_320,
} as const;

export const MAPLIBRE_TO_SMART_SEOUL_ZOOM_OFFSET = 3;
