export const SMART_SEOUL_THEME_CONTENTS_LANGUAGE = "ko";
export const SMART_SEOUL_THEME_CONTENTS_PAGE_SIZE = 100;
export const SMART_SEOUL_THEME_CONTENTS_SEARCH_DISTANCE_METERS = 50000;
export const SMART_SEOUL_THEME_CONTENTS_SUCCESS_CODES = new Set(["", "0", "200"]);
export const SMART_SEOUL_THEME_PLACES_STALE_TIME_MS = 1000 * 60 * 30;
export const SMART_SEOUL_THEME_CONTENTS_DEFAULT_MAX_PAGES = 30;
export const SMART_SEOUL_THEME_CONTENTS_SEARCH_TYPE = "0";
export const SMART_SEOUL_THEME_CONTENTS_EMPTY_SEARCH_VALUE = "";

export const SMART_SEOUL_THEME_CONTENTS_SEARCH_CENTER = {
  lng: 126.978462379,
  lat: 37.566501314,
} as const;
