name: Release Note

on:
  push:
    branches:
      - dev

jobs:
  collect-release-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install @octokit/rest @notionhq/client

      - name: Run Release Collector Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          TARGET_BRANCH: "main"
          BASE_BRANCH: "dev"
        run: node scripts/release/auto-release.js
